#!/usr/bin/env python

# MBUtil: a tool for MBTiles files
# Supports importing, exporting, and more
# 
# (c) Development Seed 2012
# Licensed under BSD

import logging, os, sys
from optparse import OptionParser

from mbutil import mbtiles_to_disk, disk_to_mbtiles, mbtiles_to_disk_gme

if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)

    parser = OptionParser(usage="""usage: %prog [options] input output
    
    Examples:
    
    Export an mbtiles file to a directory of files:
    $ mb-util world.mbtiles tiles # tiles must not already exist
    
    Import a directory of tiles into an mbtiles file:
    $ mb-util tiles world.mbtiles # mbtiles file must not already exist""")
    
    parser.add_option('--scheme', dest='scheme',
        help='''Tiling scheme of the tiles. Default is "xyz" (z/x/y),
            other option is "tms" which is also z/x/y
            but uses a flipped y coordinate''',
        type='string',
        default='xyz')

    parser.add_option('--gme', dest='gme',
        help='''Should MBUtil generate Sidecars and a .ebm file so tiles can be loaded to Google Maps Engine? Default is "false". Type "true" if you want to do this.''',
        type='string',
        default='false')

    parser.add_option('--acquisitionDate', dest='acquisitionDate',
        help='''If ---gme=true, what is the acquisitionDate for the tile set? Ex: 1982:03:13 or 2002:02:16-2012:04:23 format''',
        type='string',
        default='')

    parser.add_option('--attribution', dest='attribution',
        help='''If --gme=true, what is the Attribution Provider for the tile set? Ex: OSM or USDA FSA NAIP''',
        type='string',
        default='')

    parser.add_option('--tags', dest='tags',
        help='''If --gme=true, what are the Tags for the tile set? Ex: roads,osm,buildings or imagery,naip,Virginia''',
        type='string',
        default='')

    (options, args) = parser.parse_args()

    # Transfer operations
    if len(args) != 2:
        parser.print_help()
        sys.exit(1)

    if os.path.isfile(args[0]) and os.path.exists(args[1]):
        sys.stderr.write('To export MBTiles to disk, specify a directory that does not yet exist\n')
        sys.exit(1)
    
    # to disk
    if os.path.isfile(args[0]) and not os.path.exists(args[1]):
        if options.gme == 'true':
            mbtiles_file, directory_path = args
            mbtiles_to_disk_gme(mbtiles_file, directory_path, **options.__dict__)    
        else :
            mbtiles_file, directory_path = args
            mbtiles_to_disk(mbtiles_file, directory_path, **options.__dict__)
    
    if os.path.isdir(args[0]) and os.path.isfile(args[1]):
        sys.stderr.write('Importing tiles into already-existing MBTiles is not yet supported\n')
        sys.exit(1)
    
    # to mbtiles
    if os.path.isdir(args[0]) and not os.path.isfile(args[0]):
        directory_path, mbtiles_file = args
        disk_to_mbtiles(directory_path, mbtiles_file, **options.__dict__)
